# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\projects-summary\data-multidimensional-analysis\multidim_gui\multidim_analysis_v2.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 800)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        self.titleLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.titleLabel.setMaximumSize(QtCore.QSize(16777215, 60))
        self.titleLabel.setStyleSheet("background-color: rgb(39, 39, 39);\n"
"font: 29pt \"宋体\";\n"
"color: rgb(90, 174, 242);\n"
"color: rgb(255, 255, 255);\n"
"color: rgb(85, 255, 255);")
        self.titleLabel.setScaledContents(True)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setWordWrap(False)
        self.titleLabel.setIndent(0)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1280, 695))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setContentsMargins(0, 9, 0, 9)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, 8, -1)
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.treeWidget = QtWidgets.QTreeWidget(self.scrollAreaWidgetContents)
        self.treeWidget.setStyleSheet("font: 11pt \"微软雅黑\";\n"
"background-color: rgb(35, 35, 35);\n"
"color: rgb(85, 255, 255);\n"
"\n"
"")
        self.treeWidget.setAlternatingRowColors(False)
        self.treeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.treeWidget.setIconSize(QtCore.QSize(0, 0))
        self.treeWidget.setAutoExpandDelay(1)
        self.treeWidget.setRootIsDecorated(True)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setAllColumnsShowFocus(False)
        self.treeWidget.setWordWrap(False)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        self.treeWidget.header().setVisible(False)
        self.horizontalLayout_2.addWidget(self.treeWidget)
        self.graphLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.graphLabel.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.graphLabel.setText("")
        self.graphLabel.setObjectName("graphLabel")
        self.horizontalLayout_2.addWidget(self.graphLabel)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("background-color: rgb(29, 29, 29);\n"
"color: rgb(255, 255, 255);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1280, 23))
        self.menuBar.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"selection-background-color: rgb(100, 100, 100);\n"
"color: rgb(255, 255, 255);")
        self.menuBar.setObjectName("menuBar")
        self.processMenu = QtWidgets.QMenu(self.menuBar)
        self.processMenu.setObjectName("processMenu")
        self.setupMenu = QtWidgets.QMenu(self.menuBar)
        self.setupMenu.setObjectName("setupMenu")
        self.viewMenu = QtWidgets.QMenu(self.menuBar)
        self.viewMenu.setObjectName("viewMenu")
        self.notificationMenu = QtWidgets.QMenu(self.menuBar)
        self.notificationMenu.setObjectName("notificationMenu")
        MainWindow.setMenuBar(self.menuBar)
        self.openConfigFile = QtWidgets.QAction(MainWindow)
        self.openConfigFile.setObjectName("openConfigFile")
        self.start = QtWidgets.QAction(MainWindow)
        self.start.setObjectName("start")
        self.stop = QtWidgets.QAction(MainWindow)
        self.stop.setObjectName("stop")
        self.chen1 = QtWidgets.QAction(MainWindow)
        self.chen1.setObjectName("chen1")
        self.chen2 = QtWidgets.QAction(MainWindow)
        self.chen2.setObjectName("chen2")
        self.li = QtWidgets.QAction(MainWindow)
        self.li.setObjectName("li")
        self.yv1 = QtWidgets.QAction(MainWindow)
        self.yv1.setObjectName("yv1")
        self.yv2 = QtWidgets.QAction(MainWindow)
        self.yv2.setObjectName("yv2")
        self.wang = QtWidgets.QAction(MainWindow)
        self.wang.setObjectName("wang")
        self.pan = QtWidgets.QAction(MainWindow)
        self.pan.setObjectName("pan")
        self.yue = QtWidgets.QAction(MainWindow)
        self.yue.setObjectName("yue")
        self.fullScreen = QtWidgets.QAction(MainWindow)
        self.fullScreen.setObjectName("fullScreen")
        self.exitFullScreen = QtWidgets.QAction(MainWindow)
        self.exitFullScreen.setObjectName("exitFullScreen")
        self.openEmailReport = QtWidgets.QAction(MainWindow)
        self.openEmailReport.setObjectName("openEmailReport")
        self.processMenu.addAction(self.start)
        self.processMenu.addAction(self.stop)
        self.setupMenu.addAction(self.openConfigFile)
        self.viewMenu.addAction(self.fullScreen)
        self.viewMenu.addAction(self.exitFullScreen)
        self.notificationMenu.addAction(self.openEmailReport)
        self.menuBar.addAction(self.processMenu.menuAction())
        self.menuBar.addAction(self.viewMenu.menuAction())
        self.menuBar.addAction(self.notificationMenu.menuAction())
        self.menuBar.addAction(self.setupMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "生产流程的多维分析与可视化"))
        self.titleLabel.setText(_translate("MainWindow", "生产流程的多维分析与可视化"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "1"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "工位设备综合效率多维度分析与可视化"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "侧板焊接线"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "侧板设备工作损失占比"))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "侧板OEE能效日推图"))
        self.treeWidget.topLevelItem(0).child(0).child(2).setText(0, _translate("MainWindow", "侧板设备工作损失时间统计"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "多工位的安全监测、生产过程控制与可视化"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "专机下线"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "新萨瓦尼尼线"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "喷粉上线"))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "老萨瓦尼尼线"))
        self.treeWidget.topLevelItem(1).child(4).setText(0, _translate("MainWindow", "薄板通用线"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "多生产线的数据分析与可视化"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "侧板焊接线"))
        self.treeWidget.topLevelItem(2).child(0).child(0).setText(0, _translate("MainWindow", "焊接启动"))
        self.treeWidget.topLevelItem(2).child(0).child(1).setText(0, _translate("MainWindow", "送丝"))
        self.treeWidget.topLevelItem(2).child(0).child(2).setText(0, _translate("MainWindow", "油泵开"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "新萨瓦尼尼线"))
        self.treeWidget.topLevelItem(2).child(1).child(0).setText(0, _translate("MainWindow", "门板前左角度"))
        self.treeWidget.topLevelItem(2).child(1).child(1).setText(0, _translate("MainWindow", "门板中部左角度"))
        self.treeWidget.topLevelItem(2).child(1).child(2).setText(0, _translate("MainWindow", "门板后左角度"))
        self.treeWidget.topLevelItem(2).child(1).child(3).setText(0, _translate("MainWindow", "门板前右角度"))
        self.treeWidget.topLevelItem(2).child(1).child(4).setText(0, _translate("MainWindow", "门板中部右角度"))
        self.treeWidget.topLevelItem(2).child(1).child(5).setText(0, _translate("MainWindow", "门板后右角度"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "多生产设备的PLC节点的数据分析与可视化显示"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "OP20线"))
        self.treeWidget.topLevelItem(3).child(0).child(0).setText(0, _translate("MainWindow", "OP20今日报警频次"))
        self.treeWidget.topLevelItem(3).child(0).child(1).setText(0, _translate("MainWindow", "OP20一周报警情况"))
        self.treeWidget.topLevelItem(3).child(0).child(2).setText(0, _translate("MainWindow", "OP20侧气压低"))
        self.treeWidget.topLevelItem(3).child(0).child(3).setText(0, _translate("MainWindow", "OP20冲床报警"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "OP30线"))
        self.treeWidget.topLevelItem(3).child(1).child(0).setText(0, _translate("MainWindow", "OP30今日报警频次"))
        self.treeWidget.topLevelItem(3).child(1).child(1).setText(0, _translate("MainWindow", "OP30一周报警情况"))
        self.treeWidget.topLevelItem(3).child(1).child(2).setText(0, _translate("MainWindow", "OP30机器人急停"))
        self.treeWidget.topLevelItem(3).child(1).child(3).setText(0, _translate("MainWindow", "OP30码垛产品不一致"))
        self.treeWidget.topLevelItem(3).child(2).setText(0, _translate("MainWindow", "OP40线"))
        self.treeWidget.topLevelItem(3).child(2).child(0).setText(0, _translate("MainWindow", "OP40今日报警频次"))
        self.treeWidget.topLevelItem(3).child(2).child(1).setText(0, _translate("MainWindow", "OP40一周报警情况"))
        self.treeWidget.topLevelItem(3).child(2).child(2).setText(0, _translate("MainWindow", "OP40安全门未锁"))
        self.treeWidget.topLevelItem(3).child(2).child(3).setText(0, _translate("MainWindow", "OP40宽度检测气缸缩回未到位"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.processMenu.setTitle(_translate("MainWindow", "程序"))
        self.setupMenu.setTitle(_translate("MainWindow", "设置"))
        self.viewMenu.setTitle(_translate("MainWindow", "显示"))
        self.notificationMenu.setTitle(_translate("MainWindow", "通知"))
        self.openConfigFile.setText(_translate("MainWindow", "打开配置文件"))
        self.start.setText(_translate("MainWindow", "启动"))
        self.stop.setText(_translate("MainWindow", "终止"))
        self.chen1.setText(_translate("MainWindow", "智能异常事件监测与保护系统"))
        self.chen2.setText(_translate("MainWindow", "产品工件智能角度检测系统"))
        self.li.setText(_translate("MainWindow", "传感器数据采集分析与可视化系统"))
        self.yv1.setText(_translate("MainWindow", "生产线报警智能检测分析系统"))
        self.yv2.setText(_translate("MainWindow", "工厂CPS产线建模与分析系统"))
        self.wang.setText(_translate("MainWindow", "工厂侧板效率智能检测系统"))
        self.pan.setText(_translate("MainWindow", "产品包装配件完整性监测系统"))
        self.yue.setText(_translate("MainWindow", "厚板线OEE效率检测系统"))
        self.fullScreen.setText(_translate("MainWindow", "全屏模式"))
        self.exitFullScreen.setText(_translate("MainWindow", "退出全屏"))
        self.openEmailReport.setText(_translate("MainWindow", "发送邮件报告"))
